name: Release to TER
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  tag-valid:
    name: Check for valid tag
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-tag.outputs.match }}
    steps:
      - name: Check if trigger is a valid tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
          fi
  ter-release:
    name: Release to TYPO3 TER
    needs: tag-valid
    if: needs.tag-valid.outputs.status == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [8.1]
    env:
      TYPO3_EXTENSION_KEY: bw_jobs
      TYPO3_USER: ${{ secrets.TYPO3_USER }}
      TYPO3_PASSWORD: ${{ secrets.TYPO3_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.TYPO3_EXTENSION_KEY }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, xml, soap, zip, curl

      - name: Install TYPO3 TER client
        run: composer global require namelesscoder/typo3-repository-client "^2.0" --prefer-dist --no-progress --no-suggest

      - name: Remove .git folder
        run: rm -rf ./$TYPO3_EXTENSION_KEY/.git

      - name: List extension folder
        run: ls -liAsh ./$TYPO3_EXTENSION_KEY

      # - name: Upload EXT:${{ env.TYPO3_EXTENSION_KEY }} as ${{ github.event.ref }} to TER
      #   run: php ~/.composer/vendor/bin/upload "./$TYPO3_EXTENSION_KEY" "$TYPO3_USER" "$TYPO3_PASSWORD" "${{ github.event.head_commit.message }}"
